# Generated by Django 4.0.4 on 2022-05-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardCvv',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardMonth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardNumber',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardYear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='postalCode',
            field=models.IntegerField(),
        ),
    ]
