# Generated by Django 4.0.4 on 2022-05-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_payment_cardcvv_alter_payment_cardmonth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardCvv',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardNumber',
            field=models.IntegerField(max_length=17),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardholderName',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='payment',
            name='city',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='payment',
            name='country',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='payment',
            name='location',
            field=models.CharField(max_length=250),
        ),
    ]
