# Generated by Django 4.0.4 on 2022-05-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_payment_item_alter_payment_cardcvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='item',
        ),
        migrations.AddField(
            model_name='payment',
            name='bid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.bids'),
            preserve_default=False,
        ),
    ]
