# Generated by Django 4.0.4 on 2022-05-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_payment_item_payment_bid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
