# Generated by Django 4.0.4 on 2022-05-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_name_profile_user_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.condition'),
        ),
    ]
