# Generated by Django 4.0.4 on 2022-05-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_condition_alter_item_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
