# Generated by Django 4.0.4 on 2022-05-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_sellerrating_rename_user_rating_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
