# Generated by Django 4.0.4 on 2022-05-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userinfo_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
    ]
